
set(libprotobuf_lite_files
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/any_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_align.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenastring.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenaz_sampler.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/extension_set.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_enum_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/implicit_weak_message.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/inlined_string_field.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/coded_stream.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/io_win32.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/message_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/parse_context.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/raw_ptr.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_field.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_ptr_field.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/common.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wire_format_lite.cc
)

set(libprotobuf_lite_includes
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/any.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_align.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_allocation_policy.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_cleanup.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenastring.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenaz_sampler.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/endian.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/explicitly_constructed.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/extension_set.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/extension_set_inl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_enum_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_decl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_impl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/has_bits.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/implicit_weak_message.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/inlined_string_field.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/internal_visibility.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/coded_stream.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/io_win32.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_field_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_type_handler.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/message_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/metadata_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/parse_context.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port_def.inc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port_undef.inc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/raw_ptr.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_field.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_ptr_field.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/serial_arena.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/string_block.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/callback.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/common.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/platform_macros.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/port.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/status_macros.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/thread_safe_arena.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/varint_shuffle.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wire_format_lite.h
)

set(libprotobuf_files
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/any.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/api.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/duration.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/empty.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/field_mask.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/source_context.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/struct.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/timestamp.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/type.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wrappers.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/any.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/any_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_align.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenastring.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenaz_sampler.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/compiler/importer.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/compiler/parser.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/cpp_features.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor.pb.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor_database.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/dynamic_message.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/extension_set.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/extension_set_heavy.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/feature_resolver.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_enum_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_bases.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_reflection.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_full.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_gen.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/implicit_weak_message.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/inlined_string_field.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/internal_message_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/coded_stream.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/gzip_stream.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/io_win32.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/printer.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/strtod.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/tokenizer.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_sink.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/lexer.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/message_path.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/parser.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/unparser.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/untyped_message.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/writer.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/zero_copy_buffered_stream.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/json.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_field.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/message.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/message_lite.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/parse_context.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/raw_ptr.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/reflection_mode.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/reflection_ops.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_field.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_ptr_field.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/service.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/common.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/text_format.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/unknown_field_set.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/delimited_message_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/field_comparator.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/field_mask_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/message_differencer.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/time_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/type_resolver_util.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wire_format.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wire_format_lite.cc
)

set(libprotobuf_includes
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/any.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/api.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/duration.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/empty.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/field_mask.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/source_context.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/struct.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/timestamp.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/type.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wrappers.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/any.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_align.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_allocation_policy.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arena_cleanup.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenastring.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/arenaz_sampler.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/compiler/importer.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/compiler/parser.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/cpp_edition_defaults.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/cpp_features.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor.pb.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor_database.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/descriptor_visitor.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/dynamic_message.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/endian.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/explicitly_constructed.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/extension_set.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/extension_set_inl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/feature_resolver.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/field_access_listener.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_enum_reflection.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_enum_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_bases.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_reflection.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_decl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_gen.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_tctable_impl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/generated_message_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/has_bits.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/implicit_weak_message.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/inlined_string_field.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/internal_message_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/internal_visibility.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/coded_stream.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/gzip_stream.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/io_win32.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/printer.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/strtod.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/tokenizer.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_sink.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/io/zero_copy_stream_impl_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/descriptor_traits.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/lexer.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/message_path.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/parser.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/parser_traits.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/unparser.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/unparser_traits.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/untyped_message.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/writer.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/internal/zero_copy_buffered_stream.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/json/json.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_entry.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_field.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_field_inl.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_field_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/map_type_handler.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/message.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/message_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/metadata.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/metadata_lite.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/parse_context.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port_def.inc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/port_undef.inc
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/raw_ptr.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/reflection.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/reflection_internal.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/reflection_mode.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/reflection_ops.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_field.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/repeated_ptr_field.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/serial_arena.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/service.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/string_block.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/callback.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/common.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/platform_macros.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/port.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/stubs/status_macros.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/text_format.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/thread_safe_arena.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/unknown_field_set.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/delimited_message_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/field_comparator.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/field_mask_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/json_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/message_differencer.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/time_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/type_resolver.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/util/type_resolver_util.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/varint_shuffle.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wire_format.h
${CMAKE_CURRENT_SOURCE_DIR}/src/google/protobuf/wire_format_lite.h
)
#add_library(libprotobuf_lite ${libprotobuf_lite_files} ${libprotobuf_includes})
#add_library(libprotobuf ${libprotobuf_files} ${libprotobuf_includes})
#target_link_libraries(libprotobuf_lite ${THREAD_LIBRARY})
#target_link_libraries(libprotobuf ${THREAD_LIBRARY})

#set_target_properties(libprotobuf PROPERTIES
#      PREFIX ""
#      FOLDER "opt")
#set_target_properties(libprotobuf_lite PROPERTIES
#      PREFIX ""
#      FOLDER "opt")

add_library(PROTOBUF_LITE_LIB OBJECT ${libprotobuf_lite_files} ${libprotobuf_includes})
add_library(PROTOBUF_LIB OBJECT ${libprotobuf_files} ${libprotobuf_includes})
