// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/compiler/cpp/test_large_enum_value.proto
// Protobuf C++ Version: 4.26.0-dev

#include "google/protobuf/compiler/cpp/test_large_enum_value.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf_unittest {
      template <typename>
PROTOBUF_CONSTEXPR TestLargeEnumValue::TestLargeEnumValue(::_pbi::ConstantInitialized) {}
struct TestLargeEnumValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestLargeEnumValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestLargeEnumValueDefaultTypeInternal() {}
  union {
    TestLargeEnumValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestLargeEnumValueDefaultTypeInternal _TestLargeEnumValue_default_instance_;
}  // namespace protobuf_unittest
static ::_pb::Metadata file_level_metadata_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto = nullptr;
const ::uint32_t
    TableStruct_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protobuf_unittest::TestLargeEnumValue, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::protobuf_unittest::TestLargeEnumValue)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf_unittest::_TestLargeEnumValue_default_instance_._instance,
};
const char descriptor_table_protodef_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n8google/protobuf/compiler/cpp/test_larg"
    "e_enum_value.proto\022\021protobuf_unittest\"J\n"
    "\022TestLargeEnumValue\"4\n\022EnumWithLargeValu"
    "e\022\013\n\007VALUE_1\020\001\022\021\n\tVALUE_MAX\020\377\377\377\377\007"
};
static ::absl::once_flag descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto = {
    false,
    false,
    153,
    descriptor_table_protodef_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto,
    "google/protobuf/compiler/cpp/test_large_enum_value.proto",
    &descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto::offsets,
    file_level_metadata_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto,
    file_level_enum_descriptors_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto,
    file_level_service_descriptors_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto_getter() {
  return &descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto;
}
namespace protobuf_unittest {
const ::google::protobuf::EnumDescriptor* TestLargeEnumValue_EnumWithLargeValue_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto);
  return file_level_enum_descriptors_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TestLargeEnumValue_EnumWithLargeValue_internal_data_[] = {
    65537u, 65536u, 2147483647u, };
bool TestLargeEnumValue_EnumWithLargeValue_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, TestLargeEnumValue_EnumWithLargeValue_internal_data_);
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr TestLargeEnumValue_EnumWithLargeValue TestLargeEnumValue::VALUE_1;
constexpr TestLargeEnumValue_EnumWithLargeValue TestLargeEnumValue::VALUE_MAX;
constexpr TestLargeEnumValue_EnumWithLargeValue TestLargeEnumValue::EnumWithLargeValue_MIN;
constexpr TestLargeEnumValue_EnumWithLargeValue TestLargeEnumValue::EnumWithLargeValue_MAX;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class TestLargeEnumValue::_Internal {
 public:
};

TestLargeEnumValue::TestLargeEnumValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:protobuf_unittest.TestLargeEnumValue)
}
TestLargeEnumValue::TestLargeEnumValue(
    ::google::protobuf::Arena* arena,
    const TestLargeEnumValue& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  TestLargeEnumValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:protobuf_unittest.TestLargeEnumValue)
}









::google::protobuf::Metadata TestLargeEnumValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto_getter,
                                   &descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto_once,
                                   file_level_metadata_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf_unittest
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_google_2fprotobuf_2fcompiler_2fcpp_2ftest_5flarge_5fenum_5fvalue_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
